### ISSUE TITLE
Using the stack without ingress

### ISSUE THREAD

**Issue by xaocon** [bitnami/kube-prod-runtime#1131]
I'm looking for any documentation or past experience that could help with deploying the runtime without the ingress stack.

We're quite happy with our current ingress stack and I don't want to move away from it but I like the idea of the runtime since we've been moving more and more to bitnami charts anyways. We use some of the charts with our current ingress already so that part isn't a problem. I'm just wondering if there's a good way to disable it in the configs rather than going through and removing portions from the jsonnet and if there are any foreseen pitfalls from leaving them out.

**Comment by javsalgar** [comment]
Hi,

So far, I believe that the only way would be to change the your deployment jsonnet and remove the part that deploys ingress. I don't believe there should be issues with that.

**Comment by xaocon** [comment]
OK, I'll close this and if I come across a problem I'll open something up so there will at least be some kind of tracking.
