### ISSUE TITLE
Install Apache Airflow

### ISSUE THREAD

**Issue by raefezzeldin** [bitnami/kube-prod-runtime#1145]
I am trying to install bitnami Airflow on BKPR to utilize the tls , logging and authorization features after install the image this error appears to me 

 Error parsing headers: 'limit request headers fields size'

**Comment by javsalgar** [comment]
Hi,

This seems to be an issue related with the chart itself. Could you provide more details in the github.com/bitnami/charts repository?

**Comment by raefezzeldin** [comment]
is there any clear steps how to configure DNS and Certificates. when I deploy new app on KupeProd. or it is just for Kupe Prod only.

**Comment by javsalgar** [comment]
From the README.md here https://github.com/bitnami/charts/tree/master/bitnami/airflow you would need to set 

```
ingress.enabled=true
ingress.certManager=true
```

With that, the cert-manager installation in KubeProd would configure the domain for the Airflow installation.

**Comment by raefezzeldin** [comment]
but how to set ssl certificates for the webserver?
 "AIRFLOW__WEBSERVER__WEB_SERVER_SSL_CERT"
 "AIRFLOW__WEBSERVER__WEB_SERVER_SSL_KEY"

**Comment by javsalgar** [comment]
Let's continue the conversation here https://github.com/bitnami/charts/issues/5876 as it is related to the chart
