### ISSUE TITLE
Can't install kubeprod

### ISSUE THREAD

**Issue by raefezzeldin** [bitnami/kube-prod-runtime#1181]
When I try to install kubeprod using

kubeprod install aks \
    --email ${AZURE_USER} \
    --dns-zone "${AZURE_DNS_ZONE}" \
    --dns-resource-group "${AZURE_RESOURCE_GROUP}"

Error appears to me
 `required flag(s) "manifests" not set`

**Comment by javsalgar** [comment]
Hi,

Could you specify which kubeprod version you are using? In which OS you are running kubeprod?

**Comment by raefezzeldin** [comment]
I was using v1.7 when I used manifiest flag it worked fine but I got a new error related to service principle so what privileges I am missing 

 Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an 
error. Status=400 Code="PrincipalNotFound" Message="Principal XXXXXXXXXXXXXXX does not exist in the directory XXXXXXXXXXXXXXXXXX."

**Comment by raefezzeldin** [comment]
however I have checked the registered application and I found it exist

**Comment by raefezzeldin** [comment]
> Hi,
> 
> 
> 
> Could you specify which kubeprod version you are using? In which OS you are running kubeprod? 

I am instaling kubeprod on aks from Ubuntu

**Comment by javsalgar** [comment]
Could you specify which manifest  you set as the parameter?

**Comment by raefezzeldin** [comment]
./bin/kubeprod install aks \
    --email "${AZURE_USER}" \
    --manifests ../manifests \
    --dns-zone "${AZURE_DNS_ZONE}" \
    --dns-resource-group "${AZURE_RESOURCE_GROUP}"

I am using the manifests from the GitHub Repo github.com/bitnami/kube-prod-runtime/kubeprod

**Comment by raefezzeldin** [comment]
> Could you specify which manifest  you set as the parameter? 

I am using the exists in the kubeprod runtime github repo

**Comment by javsalgar** [comment]
Pinging @scottmuc as it may be related to the latest release 3 days ago

**Comment by scottmuc** [comment]
Hi @raefezzeldin, I'm familiar with the error message you're getting. It came up during my manual testing in Azure.

Unfortunately with the current build, the resolution is as follows:

* delete the DNS zone
* delete the 2 App Registrations
* try the installer again

From what I've figured out, it's related to the code here: https://github.com/bitnami/kube-prod-runtime/blob/master/kubeprod/pkg/aks/platform.go#L52-L70

I'll bump the timeout in `1.7.1` in the short term. I'll propose a more robust poll and timeout implementation for `1.8` and above. I'll investigate the `--manifests` argument error in my `1.7.1` testing.

**Comment by raefezzeldin** [comment]
Hi @scottmuc ,

thanks for your reply. I have used the new  pre -release  and facing the same issue Principle not Found however it is created.

**Comment by raefezzeldin** [comment]
@scottmuc  is the issue related to the region I am currently using west europe

**Comment by scottmuc** [comment]
I don't believe so. I can do a quick test of it though.

My theory on this issue is that `kubeprod` creates an `App Registration`. Later it tries to retrieve the `Principal` for this registration. I believe there's an async problem where the read attempt is not retrieving the `Principal` either because it hasn't finished creating yet, or the queryable interface for this object hasn't been refreshed to know that the object exists. 

I've had to retry 3-4 times to get it to work unfortunately :-(

The reason I feel 1.8 may resolve this is that I'll be working on fixing the CI pipeline (which does a sweet of installation + integration tests). Fixing this issue will eliminate some flakiness in the pipeline and will make all of our lives a bit easier.

**Comment by raefezzeldin** [comment]
hi @scottmuc 

thanks for your reply. I hope 1.8 will be released ASAP. as I am pending on it. however I have installed it before but on a different subscription. and it worked fine.

**Comment by raefezzeldin** [comment]
hi @scottmuc 
I have used another aks account and it worked fine. I think may be it is related to my role on the other account.

**Comment by scottmuc** [comment]
@raefezzeldin `v1.7.1` is released now. It's no different than `v1.7.1-rc1` except for the version string. We've been running this version in our clusters for a while. I'm going to close this issue for now. I'll be getting back to release `v1.8.x` once I return from some annual leave.
