### ISSUE TITLE
Split Prometheus configuration and rules in two different configmaps

### ISSUE THREAD

**Issue by dbarranco** [bitnami/kube-prod-runtime#188]
Currently kubeprod deploys one ConfigMap for the Prometheus deployment that includes the following:

* `monitoring.yml` -> Rules file
* `basic.yml` -> Rules file
* `prometheus.yml` -> Prometheus configuration

An approach we've found useful while implementing our gitOps workflow is to split that ConfigMap in two different ones, one intended for rules and one intended for Prometheus configuration.

With this, Prometheus could be easily integrated in a gitOps workflow, and any developer could update Prometheus rules without side affecting the application configuration, integrating this with the ConfigMap-reloader the deployment has.

These two new Prometheus ConfigMaps can be safely mounted in:

* `/opt/bitnami/prometheus/conf` for application configuration
* `/opt/bitnami/prometheus/conf/rules.d` for Prometheus rules

And Prometheus will load and group them in different folders, as it currently works.

Of course, happy to share with you the work the SRE team did around this :) 
cc/ @jjo @jbianquetti-nami

**Comment by jbianquetti-nami** [comment]
Also, `configmap-reloader` should take care of  @dbarranco's  proposed directories. 

Snippet:

~~~
--- skipped ---
     - args:
        - --volume-dir=/opt/bitnami/prometheus/conf
        - --volume-dir=/opt/bitnami/prometheus/conf/rules.d
        - --webhook-url=http://localhost:9090/-/reload
        image: jimmidyson/configmap-reload:v0.1
        imagePullPolicy: IfNotPresent
        name: configmap-reload
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/bitnami/prometheus/conf
          name: config
          readOnly: true
        - mountPath: /opt/bitnami/prometheus/conf/rules.d
          name: rules
          readOnly: true
--- skipped ---
~~~

**Comment by falfaro** [comment]
We have decided to switch to using Prometheus Operator instead.

I'm closing this bug. If you have any concerns, feel free to re-open it.
Thanks!
