### ISSUE TITLE
Get the latest version of Kubeprod releases in docs programatically

### ISSUE THREAD

**Issue by dbarranco** [bitnami/kube-prod-runtime#189]
As I was looking this morning at the GKE quick start docs I noticed we are pointing users to to the releases tab of Github to find the latest release of Kubeprod to create the `BKPR_VERSION` environment variable.

Just wanted to point what we did in other repositories like SealedSecrets:

`$ release=$(curl --silent "https://api.github.com/repos/bitnami-labs/sealed-secrets/releases/latest" | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p')`

[ref](https://github.com/bitnami-labs/sealed-secrets/blob/master/README.md#installation)

Making easier to users to follow the docs without leaving the documentation page  :)

**Comment by dbarranco** [comment]
sure, why not! :) 
will create one addressing this

**Comment by dbarranco** [comment]
Created https://github.com/bitnami/kube-prod-runtime/pull/211

**Comment by dbarranco** [comment]
@arapulido now that this issue is solved should I close it? (Just asking as I saw you moved that to _Done_)

**Comment by sameersbn** [comment]
yes, we can close this.
