### ISSUE TITLE
Provide Homebrew tap to install kubeprod 

### ISSUE THREAD

**Issue by jbianquetti-nami** [bitnami/kube-prod-runtime#195]
https://docs.brew.sh/Taps

**Comment by sameersbn** [comment]
PR submitted https://github.com/Homebrew/homebrew-core/pull/35901

**Comment by sameersbn** [comment]
Until the PR is merged, you can use the following commands to install kubeprod from the tap

```bash
brew tap sameersbn/core
brew install sameersbn/core/kubeprod
```

**Comment by sameersbn** [comment]
PR has been merged. You should now find `kubeprod` in homebrew core
