### ISSUE TITLE
`config` and `apply` subcommands

### ISSUE THREAD

**Issue by arapulido** [bitnami/kube-prod-runtime#196]
As discussed int [the UX document for the CLI](https://docs.google.com/document/d/13NHDbZyzFg20LRag0eLRJPThIEYP0GeWCX-L4f2gv2Y/edit), we want the install command to be a composed command that can be split into config and apply

Right now only the install command exists. We should create the subcommands config and apply

**Comment by falfaro** [comment]
It is probably best to just implement a new subcommand named like `generate` which creates all the relevant objects in the underlying platform (GKE, AKS) and then generates the JSON configuration file and jsonnet root manifests.

From that point, users can customise the root manifest at will and then run `kubeprod install` to deploy the changes to production. No need for a `kubeprod apply` subcommand.

**Comment by anguslees** [comment]
PR #232 probably addresses this issue, but not with the solution(s) described above.

**Comment by anguslees** [comment]
Fixed in #232
