### ISSUE TITLE
heapster is installed into wrong namespace (kubeprod)

### ISSUE THREAD

**Issue by anguslees** [bitnami/kube-prod-runtime#217]
We want heapster to exist in the cluster (for clusters before 1.11(?) when we switch to metrics-server).

Heapster must exist in `kube-system` to be useful, since that's where the `kubectl top nodes`, k8s dashboard, HPA controller, etc [look for it](https://github.com/kubernetes/kubernetes/blob/2d09bfe951f59090f64fa131ea6f1a0cc7b3e008/pkg/kubectl/metricsutil/metrics_client.go#L34).  Installing heapster in `kubeprod` namespace is just a waste of resources.

**Action items:**
- [x] audit which platforms already have a functional heapster in their default cluster install, and skip installing "our" heapster for those platforms
- [x] ~move our heapster from kubeprod -> kube-system~ remove heapster component
- [ ] ~integration test that confirms heapster is accessible at the assumed kube-system/heapster Service~ 

(note for integration test: don't wait until metrics are available, since that can take 30 minutes)

**Comment by sameersbn** [comment]
I audited all supported platforms and found that heapster is installed in each of them by default. BKPR installs `heapster` only for the AKS platform. We can go ahead and remove this component from the manifests altogether.
