### ISSUE TITLE
404 during installation

### ISSUE THREAD

**Issue by migmartri** [bitnami/kube-prod-runtime#241]
The following instructions do not work since https://github.com/bitnami/kube-prod-runtime/releases/download/v0.3.1/bkpr-v0.3.1-linux-amd64.tar.gz returns 404. This seems to be due to the fact that `BKPR_VERSION` is set to the stable release not to the pre-release and the stable release is actually called `kubeprod` (`kubeprod-v0.3.1-linux-amd64.tar.gz`) 

```
BKPR_VERSION=$(curl --silent "https://api.github.com/repos/bitnami/kube-prod-runtime/releases/latest" | jq -r '.tag_name')
curl -LO https://github.com/bitnami/kube-prod-runtime/releases/download/${BKPR_VERSION}/bkpr-${BKPR_VERSION}-linux-amd64.tar.gz
tar xf bkpr-${BKPR_VERSION}-linux-amd64.tar.gz
```

**Comment by jayzeng** [comment]
@migmartri I spotted the same error, the correct link should be:
https://github.com/bitnami/kube-prod-runtime/releases/download/v0.3.1/kubeprod-v0.3.1-linux-amd64.tar.gz (btw, you can see all available releases here: https://github.com/bitnami/kube-prod-runtime/releases/)

interestingly, the 1.0 version `does` follows this convention. E.g:
https://github.com/bitnami/kube-prod-runtime/releases/download/v1.0.0-rc5/bkpr-v1.0.0-rc5-linux-amd64.tar.gz

I guess this is likely a typo in the 0.3.1 release name.

**Comment by anguslees** [comment]
Urgh.  Yes, your assessment above is correct - we changed the artifact name between 0.3.1 and 1.0.0(-rc).

Given that the "real" 1.0 release is imminent, and it is hard/impossible to rename the existing 0.3.1 github artifacts, I'm going to close this as wontfix.  It's a real bug, however, so thank you both for the report and investigation!

Aside: For your testing, I strongly recommend you both use the 1.0.0-rc candidates.
