### ISSUE TITLE
BKPR docs should have a cluster requirements section

### ISSUE THREAD

**Issue by dbarranco** [bitnami/kube-prod-runtime#253]
In order to give more information to potential users that are going to install BKPR in a running K8s cluster, it would be nice to have a cluster requirements section with information about the minimum number of instances (and type) is required to run BKPR in each platform.

It also would be nice to think on adding compliance tests before installing kubeprod in a running cluster (to ensure that cluster is ready to have kubeprod installed). In example:
https://github.com/heptio/sonobuoy

**Comment by sameersbn** [comment]
ref: https://github.com/bitnami/kube-prod-runtime#requirements

**Comment by arapulido** [comment]
@dbarranco We have a minimum requirements section already. Please, reopen and add more details if this doesn't meet your needs.
