### ISSUE TITLE
Prometheus datasource not configured correctly in Grafana

### ISSUE THREAD

**Issue by sameersbn** [bitnami/kube-prod-runtime#259]
The Access method for the Prometheus datasource is not configured in Grafana making the datasource unusable. 

![screenshot_2018-12-05 grafana - prometheus stats](https://user-images.githubusercontent.com/410147/49497628-e07af880-f88e-11e8-905a-d70395a32261.png)

**Comment by falfaro** [comment]
Fixed by PR #260
