### ISSUE TITLE
Add support for Oracle OKE

### ISSUE THREAD

**Issue by nomisbeme** [bitnami/kube-prod-runtime#281]
Oracle provides a public Kubernetes-certified platform:
https://cloud.oracle.com/containers/kubernetes-engine

It would be great to add this as a supported platform, where OKE and kube-prod-runtime support the same Kubernetes versions.
https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengoverview.htm

There are free credits available in some countries that might be helpful for compatibility testing:
https://cloud.oracle.com/trial

**Comment by sameersbn** [comment]
#731 closes this issue
