### ISSUE TITLE
BKPR on GKE Quickstart

### ISSUE THREAD

**Issue by nomisbeme** [bitnami/kube-prod-runtime#285]
I'm following the BKPR quickstart on GKE found here:
https://github.com/bitnami/kube-prod-runtime/blob/master/docs/quickstart-gke.md

The page describes setting the GCLOUD_REGION variable as follows:

> GCLOUD_REGION specifies the Google Cloud region. gcloud compute regions list lists the available Google Cloud regions.

However the example lists a zone as the value "us-east1-d" This is further confused by the section below, which also references regions and suggests using ```gcloud compute regions list``` to get a list of possible values.

In my run I set the GCLOUD_REGION=us-west2-c and my cluster appears to have deployed correctly, at least in this regard. If you could clarify what the intended value is I can prepare a PR with some improved text for this quickstart for your review?

**Comment by sameersbn** [comment]
Thanks for reporting this issue @nomisbeme. I've corrected the error in #298. I'd be happy to have your review there.
