### ISSUE TITLE
subdomain as a DNS zone

### ISSUE THREAD

**Issue by timuckun** [bitnami/kube-prod-runtime#299]
I have my main TLD managed by GCP DNS service. I wanted to set up multiple clusters for different environments such as staging.tld.com production.tld.com etc.  I installed BKPR in one of my clusters and gave it a subdomain as the  BKPR_DNS_ZONE variable. It set up a DNS zone with the subdomain none of the hostnames in that zone resolve without further intervention.

Can BKPR use an existing zone in GCP but just add a prefix (or a suffix) to the host names? For example instead of setting up a separate staging.tld.com zone just set up an entry in the tld.com zone with grafana.staging.tld.com

**Comment by sameersbn** [comment]
Hi @timuckun 

> Can BKPR use an existing zone in GCP but just add a prefix (or a suffix) to the host names?

Yes just specify BKPR_DNS_ZONE=tld.com. But you will have to take one additional manual step of deleting the zone that BKPR creates in your GCP account.

**Description**:

When you execute `kuberprod install` the installer tool creates a zone for the domain specified in BKPR_DNS_ZONE. The name of the zone will be prefixed with `bkpr-`, f.e. if you specify `BKPR_DNS_ZONE=example.com`, then the new zone will be named `bkpr-example-com`. 

As a result you will now have two zones for `example.com` (this can be found in https://console.cloud.google.com/net-services/dns/zones). All you need to do is delete the one BKPR creates (`bkpr-example-com` in our example). After the deletion there will just be one zone for `example.com` and BKPR will only update the records that it created and not interfere with any of the existing records.



 This can be found at

**Comment by sameersbn** [comment]
@gus I think we can improve the installer in this scenario if we could detect that a zone already exists and re-use it. This is the behavior with AKS, but not with GKE

**Comment by anguslees** [comment]
@timuckun right, for simplicity the `kubeprod install` command assumes the managed zone and domain suffix are the same.  The easy version is to just create a few NS records for "staging.tld.com" in "tld.com" (and for other sub-zones as required), and allow BKPR to continue to have it's own zone to manage.

---

**The hard version:**

If you are willing to tweak a few settings manually then ExternalDNS (which BKPR includes) _can_ use a domain suffix within an existing parent zone (and even share the parent zone with other instances of ExternalDNS just fine).

You need to:
1. Configure ExternalDNS to use a service account with privileges to modify your GCP tld.com zone (at least read/write to cloud-dns)
2. Tell BKPR to use "staging.tld.com" (or similar) for everything else.

If you have already run `kubeprod install gke ...`, just take a look at the generated `kubeprod-autogen.json`.  You need to modify it to look like:
```javascript
{
   "dnsZone": "staging.tld.com",
   "externalDns": {
      "credentials": "<string containing GCP service account json credentials for modifying tld.com>",
      "project": "<GCP project containing tld.com zone>"
   },
   // leave other fields unmodified
}
```

You need to also _remove_ any "staging.tld.com" GCP zone that was created by the installer.

Now re-run `kubeprod install gke ...` from the directory containing the modified `kubeprod-autogen.json` and it should pick up the changes and push out the new config.  If the cluster was already running, you might need to manually delete the external-dns pod (in `kubeprod` namespace) to force it to restart with the new credentials, to workaround #64 .

I have just written the above from memory, so may have overlooked something.  If you try this, please followup with a success/failure report so we can improve it for anyone else who stumbles across this in future.

**Comment by timuckun** [comment]
Thanks. 

I am closing the ticket as all my questions were answered.

**Comment by EamonKeane** [comment]
I'd also like to use a custom domain. Not a dns expert, but I tried both combinations on Google Cloud-DNS @anguslees and it didn't seem to work for me, stuck with `http-01 self check failed for domain`.

For the easy version, was the suggestion to do the following?

* Set `${BKPR_DNS_ZONE}` to `staging.tld.com`
* run `kubeprod install ..`
* Add the 4 ns records (e.g. ns-cloud-a1.googledomains.com., ns-cloud-a2.googledomains.com., ns-cloud-a3.googledomains.com., ns-cloud-a4.googledomains.com.) in the `bkpr-staging` newly created zone as an entry in `tld.com` under `staging.tld.com`

I had a quick look at external DNS helm chart and didn't see much for setting sub-domain.

**Comment by EamonKeane** [comment]
Nevermind, got the easy version working. I had to change the redirect uris also!

I'd consider making this sub-domain install the default as probably a lot more folks can spare a subdomain than have a full domain to test with.

Nice.... I have a feeling kubeprod paired with jx (or something new) will change the game in the next couple years, leaving helm possibly for the last mile of end user applications.
