### ISSUE TITLE
Grafana Default Dashboards

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#306]
This is probably on your list of things to do, but do you plan on adding a default set of k8s dashboards for grafana? I have a set that I borrowed from GKE's marketplace, but they don't all fully work (due to change in node exporter format from Prometheus). I haven't come across a robust set of dashboards that work out of the box recently.

https://github.com/EamonKeane/k8s-cluster-services/tree/master/cluster-svc/dashboards

**Comment by arapulido** [comment]
Thanks a lot for your suggestion @EamonKeane . Yes, this is currently in our near-future plans :)

**Comment by jjo** [comment]
Just noting upcoming breaking metrics naming changes: from https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#urgent-upgrade-notes, 
cAdvisor metris will be renamed as : `s/pod_name/pod/` and `s/container_name/container/`,
obviously breaking backwards compat, unless we relabelled those from prometheus config
in advance (which will obviously produce a this breakage itself, but maybe in a controlled manner).

**Comment by dbarranco** [comment]
hey!
I have been taking a look at some popular dashboards to have an idea of what could I include as defaults dashboards for the Grafana BKPR and I saw that one of the most popular dashboards has been published by Bitnami:
https://grafana.com/dashboards/3119

Which is based on https://github.com/bitnami-labs/kubernetes-grafana-dashboards (repo that we don't maintain since 5 months ago).

Also, as we used that repository in some [engineering blogposts](https://engineering.bitnami.com/articles/implementing-slos-using-prometheus.html) I think it would be great if I update/refactor them in jsonnet/add some new dashboards (maybe some about EFK and Kubernetes capacity), so hopefully we can have some community contributions there too :) 

What do you think @arapulido @anguslees @jjo ? Would love to have some feedback

**Comment by sameersbn** [comment]
Please take a look at the following dashboards. They look pretty interesting.

https://grafana.com/dashboards/8685
https://grafana.com/dashboards/7249

**Comment by EamonKeane** [comment]
thanks @sameersbn a few months ago I tried several of those dashboards and unfortunately found all of them to be broken (at least on GKE 1.10). As @jjo said likely due to the ever-changing metrics names. There must be a functional set of dashboards out there somewhere but I haven't found them yet.

**Comment by arapulido** [comment]
> hey!
> I have been taking a look at some popular dashboards to have an idea of what could I include as defaults dashboards for the Grafana BKPR and I saw that one of the most popular dashboards has been published by Bitnami:
> https://grafana.com/dashboards/3119
> 
> Which is based on https://github.com/bitnami-labs/kubernetes-grafana-dashboards (repo that we don't maintain since 5 months ago).
> 
> Also, as we used that repository in some [engineering blogposts](https://engineering.bitnami.com/articles/implementing-slos-using-prometheus.html) I think it would be great if I update/refactor them in jsonnet/add some new dashboards (maybe some about EFK and Kubernetes capacity), so hopefully we can have some community contributions there too :)
> 
> What do you think @arapulido @anguslees @jjo ? Would love to have some feedback

Thanks! I think that should be a good approach.

**Comment by sameersbn** [comment]
Thanks for the information @EamonKeane. While it's true that a large number of dashboards for Kubernetes do not work properly, I normally use the  `8685` and `7249` dashboards in testing and find them to be working (including on GKE 1.10). Just for consistency, would it be possible for you to try out these two dashboards and let us know if you notice any issues with them?

While I don't fully endorse these dashboards to be included as defaults, I do find them to be pretty neat and up-to-date.

**Comment by EamonKeane** [comment]
@sameersbn ah great, tested them there and they do actually work! It might have been the combination of prometheus/grafana I was testing with.

**Comment by dbarranco** [comment]
Created https://github.com/bitnami-labs/kubernetes-grafana-dashboards/pull/13 where I updated our Grafana dashboards to make them work with node_exporter 0.17.0 and added two new dashbaords based on @sameersbn suggestions.

I modified a bit them to create a Kubernetes workload summary and a Kubernetes capacity cluster dashboard. Feel free to add yourself as a reviewers of that PR and try them :) 

Cheers

**Comment by dbarranco** [comment]
https://github.com/bitnami/kube-prod-runtime/pull/500 created

**Comment by arapulido** [comment]
This is now merged: https://github.com/bitnami/kube-prod-runtime/pull/500
