### ISSUE TITLE
GKE installs in the wrong cluster

### ISSUE THREAD

**Issue by timuckun** [bitnami/kube-prod-runtime#307]
Following the GKE quickstart instructions it installs the apps in the wrong cluster. I don't see an option to name the cluster. It seems to use whatever is set in the current-context which gets reset once you log in.

There should be an option to specifically name the cluster you are installing into. I see that there is a kubeconfig context setting in the installer, some mention of this should be made.

**Comment by falfaro** [comment]
BKPR follows the same philosophy as other Kubernetes tools and the Golang SDK that both `kubeprod` and `kubecfg` use works. That is, your `kubectl` current context should point to the cluster where you want to work or deploy with BKPR.

**Comment by falfaro** [comment]
I'm closing this as "Working as intended". Thanks!
