### ISSUE TITLE
Feature: Add Support for Digital Ocean

### ISSUE THREAD

**Issue by ptariche** [bitnami/kube-prod-runtime#309]
Add support for integration to Digital Ocean's Kubernetes Cluster offering.

**Comment by gravypower** [comment]
Hey @arapulido, 

I would be happy to give this a crack if I can get some guidance on what needs to be completed. There does not seem to be any docs on creating new providers other than the code for the existing ones.

Thanks
Aaron

**Comment by falfaro** [comment]
Hi @gravypower,

Conceptually, to support a new cloud provider, this is what we need:

- First, create a new platform manifest for Digital Ocean. See `manifests/platforms/` for reference.

There you will find implementations for AKS, GKE and EKS as of this writing. Essentially, these platform manifests implement necessary overrides for each provider. For instance, in GKE, BKPR uses Google's own authentication system for `oauth2_proxy` and use Cloud DNS for DNS integration, whereas for Amazon, BKPR will use Amazon Cognito for authentication in `oauth2_proxy` and Amazon Route53 for DNS integration. For Digital Ocean you need to figure out what authentication mechanisms are supported. `oauth2_proxy` supports OAuth2 and OpenID Connect among others.

For authentication, I believe DigitalOcean support OAuth2 natively. For DNS integration, BKPR uses External DNS which seems to support DigitalOcean natively: https://github.com/kubernetes-incubator/external-dns/blob/master/docs/tutorials/digitalocean.md

- Second, get everything working manually.

This means crafting manually a file named `kubeprod-manifest.jsonnet` that looks like this:

```
(import "../platforms/digitalocean.jsonnet") {
  config:: import "kubeprod-autogen.json",
  cert_manager+: {
    letsencrypt_environment:: "staging",
  },
}
```

What this file does is importing the DigitalOcean platform manifest, and inject a JSON configuration file. This file, named `kubeprod-autogen.json` contains data specific to your cloud. Mine for GKE keeps the OAuth2 Client ID used by `oauth2_proxy` to authenticate you, the name of the DNS zone that I am using for BKPR in Cloud DNS plus some credentials to allow External DNS to manipulate that DNS zone, etc. Again, this is cloud-specific. GKE is different from AKS and from EKS.

- Third, when you have everything working fine, authentication works, DNS integration works, etc., you will have to write Go code to automate the set up process you did manually.

For example, the Go code will try to detect whether there is already a DNS zone in DigitalOcean that you want to use for BKPR and, if not, will use the DigitalOcean API to create it. And so on and on for the authentication bits, etc. The assumption for this Go code (kubeprod) is that you already have `kubectl` configured pointing to a Kubernetes cluster running under DigitalOcean.

We can help you with the third step (writing the Go code), but if you can do the first two steps yourself it will make supporting DigitalOcean much easier and faster overall.

**Comment by gravypower** [comment]
Thanks @falfaro I will give it an attempt in the next week or so.

**Comment by imkane** [comment]
@gravypower any update?

**Comment by gravypower** [comment]
Hey @imkane,

I had my second child arrive so have been time poor, starting looking at this again yesterday. Hoping to test something later today. Will post an update when I do.

**Comment by sameersbn** [comment]
Please take a look at #731

**Comment by sameersbn** [comment]
#731 closes this issue
