### ISSUE TITLE
Add documentation about configuring components post-install

### ISSUE THREAD

**Issue by timuckun** [bitnami/kube-prod-runtime#313]
The main doc makes a reference to upgrades and support document. I don't see it anywhere.

There should also be some documentation about how to change the configuration of various components post install.

**Comment by falfaro** [comment]
There are some generic instructions for upgrading in https://github.com/bitnami/kube-prod-runtime/blob/master/docs/workflow.md.

We are working on improving our documentation so stay tuned. Oh, and please keep any feedback or suggestions or bugs you may have coming :-)

**Comment by anguslees** [comment]
Specific action items for this bug (let me know if I misunderstood/overlooked anything):

- [ ] Fix reference to upgrade+support doc to be link(s) to existing docs
- [ ] Add a doc describing how to tweak k8s config post-install (walk through adding a jsonnet override, and applying the result)

**Comment by timuckun** [comment]
My primary feedback is that this project feels like magic to most users. It does so much and presumably somebody who is deploying this into a production environment will be very concerned about what to do when things go awry.  Deploying each one of these products individually and setting them up to work together is a ton of work and there are a lot of interconnecting parts but in the end somebody might feel more comfortable doing all of that themselves even if they don't get it right because they feel like they can solve problems the problems they created.

Anything to give some assurance to the user that they will be able to comfortably deploy, troubleshoot, maintain and update this project would be immensely helpful.

Thanks.

**Comment by anguslees** [comment]
@timuckun I hear you, and this is excellent feedback.

So far we've focused our documentation efforts on the "easy" experience (which necessarily hides a lot of the details) and we have not yet described how it actually works.  This turns into making it look like magic, as you describe.  We absolutely need to put effort into documenting how it all actually works, so someone can feel confident that they can pull it to pieces and still put it back together again when required.

**Comment by arapulido** [comment]
I am currently working on this

**Comment by arapulido** [comment]
@timuckun I have organized the documentation a bit: https://github.com/bitnami/kube-prod-runtime/tree/master/docs and have added a section about config overrides: https://github.com/bitnami/kube-prod-runtime/blob/master/docs/overrides.md
