### ISSUE TITLE
How to backup or restore the persistent data.

### ISSUE THREAD

**Issue by timuckun** [bitnami/kube-prod-runtime#314]
Some products are set up as statefulsets. How do we backup or restore the volumes associated with these products.

**Comment by falfaro** [comment]
Your question is not related to BKPR. Your question depends on what is using that volume. For instance, if you are running PostgreSQL on top of a persistent volume, you have to use the backup/restore procedure specific to PostgresSQL.

But answering your question, typically you will run a co-located container next to the application that you want to back up, have that co-located container attach to the volume in read-only mode, and backup the data using something like 'rsync' or some such. In the case of backup and/or restore, you also have to deal with the process using that volume to be aware of the backup/restore.

**Comment by timuckun** [comment]
Thanks for the information.  I'll have to try and figure out how to run a co located container in one of the kube-prod pods. 

Will this be done via modifying the jsonnet file or launching a new container from a separate deployment yaml?

**Comment by arapulido** [comment]
@timuckun another way to do this is backing up the cloud disks that are created when the PVCs are created.

**Comment by arapulido** [comment]
Closing this issue, as it is not related to BKPR itself. @timuckun please, reopen it or open a new if you need more help.
