### ISSUE TITLE
Reusing BKPR oauth2 setup for custom applications

### ISSUE THREAD

**Issue by janbols** [bitnami/kube-prod-runtime#317]
I want to use KBPR's components like the oauth2-proxy for one of my applications. By configuring an ingress resource I want to route a call to myapp.mydomain.com/oauth2 to the oauth2-proxy backend in the kubepord namespace.

The problem is my application is running in the `default` namespace. Not in the `kubeprod` one. As a result, my ingress resource needs to be defined in the `default` namespace as well. As a consequence, I cannot link calls to `/oauth2` to the oauth2-proxy service b/c that's running in the `kubeprod` namespace.

Is it one of the objectives of KBPR to reuse components for custom applications? 
If so, should I just put my application in the `kubeprod` namespace? 
Should I use another oauth2-proxy in the `default` namespace instead?
Is there another way?

**Comment by falfaro** [comment]
I don't quite understand why interaction between pods running in different namespaces is not possible.

First of all, what are you using to deploy your Kubernetes application? YAML? Jsonnet? Helm?

Also, did you try deploying your Ingress resource in the `default` namespace? Does it work? If not, does it have the correct annotations? Would you mind pasting the output of `kubectl describe ingress ...` to get a better understanding of what's not working?

**Comment by anguslees** [comment]
The intention is absolutely that you can reuse the BKPR ingress/TLS/OAuth2 stack for your applications too.   Unfortunately, that goal got lost somewhere in the current implementation :(

Thanks for the report @janbols, I wasn't aware we'd messed this up until looking into it just now :(  We will fix this (with tests that exercise it from an end-users pov).

**Comment by EamonKeane** [comment]
I have a similar use case. IIUC this is a known issue and cross-namespace ingress referencing was left out intentionally for security reasons  [1], and that an `oauth2_proxy` appears to be necessary per namespace. Therefore, the solution (needed, I think) is to allow the user to specify a list of namespaces to kubprod or in jsonnet to install individual `oauth2_proxy`s into.

https://github.com/kubernetes/kubernetes/issues/17088
