### ISSUE TITLE
nginx-ingress: Increase availability during node failure

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#373]
Is the quick start intended to be HA?

I think it'd make sense to have a HA configuration - e.g. the default GKE quickstart only has one replica of nginx-ingress which will involve down-time during node upgrades. Or at least have a separate `kubeprod-manifest.jsonnet` with the over-rides.

**Comment by anguslees** [comment]
> Is the quick start intended to be HA?

Yes.  BKPR generally is intended to be (n+1) HA by default (for the data path).  ie: Losing a single node is not an emergency, but some changes (eg: new certificates) might not proceed until the cluster recovers.

There are a few ways we can improve the current nginx-ingress situation:

- Add a `PodDisruptionBudget` requiring at least one nginx-ingress to be available.  This is really the only way to ensure node upgrades don't proceed too quickly, assuming upgrades involve a `kubectl drain` (ie: clean shutdown).
- Increase to minimum 2 replicas, with host/zone (weak) anti-affinity.  This is really the only way to continue serving during a spontaneous single-node failure (ie: unclean shutdown).

I think we should do both those things by default.  The extra nginx replica will increase the minimum footprint by a small amount of ram.

Thanks for the report!  Please call out any further specific examples you find.

**Comment by EamonKeane** [comment]
yea that sounds like a good plan. The nginx-ingress had pdb of 1 and 1 replica by default which meant nodes never upgraded. So just need to verify that in the code that it's at least 2 if adding pdb.
