### ISSUE TITLE
Release 1.1.1

### ISSUE THREAD

**Issue by arapulido** [bitnami/kube-prod-runtime#375]
We should release a 1.1.1 version with all the updated images

- [x] Backport changes (#379)
- [x] Tag new release candidate (https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.1.1-rc1)
- [x] Iterate on RC releases before making final release

**Comment by sameersbn** [comment]
RC2 fixes issue with pushing image to docker hub registry
https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.1.1-rc2

**Comment by sameersbn** [comment]
[v1.1.1](https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.1.1) Released :tada:
