### ISSUE TITLE
Upgrade elasticsearch to 6.X

### ISSUE THREAD

**Issue by arapulido** [bitnami/kube-prod-runtime#376]
For next minor version (1.2) we should have updated ES to 6.x

In order to do that we should test that it still works and update the manifests and configurations

**Comment by falfaro** [comment]
EKS seems to cause problems with Elasticsearch 6.x. I've seen the following warning:

```
ERROR: [1] bootstrap checks failed
[1]: max file descriptors [8192] for elasticsearch process is too low, increase to at least [65536]
```

Reference: https://github.com/pires/kubernetes-elasticsearch-cluster/issues/215

**Comment by arapulido** [comment]
@falfaro can you open a specific issue for that, please?

**Comment by arapulido** [comment]
Closing this in favour or: https://github.com/bitnami/kube-prod-runtime/issues/427
