### ISSUE TITLE
Custom BKPR images (or startup scripts)

### ISSUE THREAD

**Issue by andrevtg** [bitnami/kube-prod-runtime#386]
I'd like to customize somehow the included images - for example, including plugins in Elasticsearch or Kibana.

Possible solutions: custom images (derived from the default bitnami ones) or custom startup scripts (mounted with custom configs/secrets/volumes/whatever).

Is there a recommended way?

Thanks!

**Comment by arapulido** [comment]
Unless you have an automated way to incorporate your changes to a new image, I would recommend the latter. If you rebuild the image, you will lose the ability to upgrade, without having to rebuild the image. One of the benefits of using BKPR is that our images are updated for security issues and other minor updates. 

What changes you need in the ES and Kibana images?

**Comment by arapulido** [comment]
@andrevtg can you tell us what type of changes you need in the images?

**Comment by anguslees** [comment]
Building custom images is out of scope for BKPR.  If you build the image somewhere else (eg: docker hub autobuild), then you can tell BKPR to _use_ that image with a normal jsonnet override - but actually building the modified image has to be done somewhere else.

For specific common cases (like grafana and elasticsearch plugins), it would indeed be good if the images (and our manifests) made that easy.  So if you have specific examples @andrevtg (or anyone else) then please request them.

For other generic modifications, BKPR supports the usual Kubernetes approaches: Inject files via configMap/secret volumeMounts (most preferred); run commands in initContainers that modify shared volumes; or by modifying the container command to run some other command before the regular container entrypoint (least preferred).

#### For grafana plugins:

The [image that BKPR uses](https://hub.docker.com/r/bitnami/grafana/) will install any plugins you declare with a `GF_INSTALL_PLUGINS` env variable (see [image docs](https://github.com/bitnami/bitnami-docker-grafana#install-plugins-at-initialization)).

#### For kibana plugins:

There is currently no _easy_ declarative method afaics :(

The solution (that you can do now) is to use a jsonnet override to add an initContainer that runs `kibana-plugin install ...`, and add a shared plugins volume between that initContainer and the regular kibana container.   That's quite a bit of jsonnet surgery, and we should offer that out of the box: I will open that as a new feature request.

#### For elasticsearch plugins: 

Set the [`ELASTICSEARCH_PLUGINS` environment variable](https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables) on the elasticsearch container(s).

**Comment by anguslees** [comment]
I'm going to close this in favour of those more specific action items I just created.  But please reopen this if you have any further customisation use-case examples you think should be covered.

**Comment by andrevtg** [comment]
Thanks!
