### ISSUE TITLE
Updating nginx-ingress Load Balancer IP

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#394]
I have a use case where I need to change the nginx-ingress IP address.

At present changing it in the below after installation has no effect. The only solution is to delete the nginx-ingress service and all ingresses and re-apply. Is this the intended behaviour?

```
// Cluster-specific configuration
(import "https://releases.kubeprod.io/files/v1.1.0/manifests/platforms/gke.jsonnet") {
	config:: import "kubeprod-autogen.json",
	nginx_ingress+: {
		svc+: {
			spec+:{
				loadBalancerIP: "35.197.193.87"
			}
		}
	}
}
```

**Comment by arapulido** [comment]
Interesting, it shouldn't be necessary to recreate the service.

I have tested this on GKE using the very simple example at: https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip 

First, without specifying a static IP (and getting an ephermeral IP) and then editing the svc yaml, adding the static IP and reapplying with `kubectl`. For some seconds, the service still had the old ephemeral IP address, but after a while, it reconfigures to the static one correctly.

How long did you wait until you considered that it wasn't working? 

Also, while the ingress service still had the old ephemeral IP, what was the output of `kubectl get svc -n kubeprod nginx_ingress - o yaml` ?

**Comment by EamonKeane** [comment]
Thanks @arapulido . I did the manual approach like you said and it worked and propagated to the ingresses.

Ah, never mind... I was lacking a space in my spec. `spec+:{`. Are there any good linting tools for jsonnet :-)

**Comment by EamonKeane** [comment]
Also just as a btw, kubeprod runtime works very well with jenkins-x. GKE + kubeprod + jenkins-x gets you a mini cloud in around 20 mins.

**Comment by anguslees** [comment]
> Ah, never mind... I was lacking a space in my spec. `spec+:{` [vs `spec+: {`]

Hrm. Glad to hear it worked out, but that space shouldn't matter... Perhaps there was some other issue, or you needed to wait longer for things to converge?  In particular, (re)creating loadbalancers can take 5+ minutes on most clouds (gke included).

**Comment by anguslees** [comment]
Oh and re jsonnet linting tools:
- The upstream [jsonnet](https://jsonnet.org/) project has a `jsonnet` tool that will check or reformat your file according to a configured coding style (whitespace choices, etc).
- The basic `jsonnet` tool can do simple syntax validation, or `kubecfg validate` can do that _and_ verify the result against the k8s schema.

I don't know of a jsonnet "lint" tool that will detect common non-syntax errors (the language is simple enough that there aren't many classes of those).

**Comment by EamonKeane** [comment]
@anguslees Ah, right you are, thanks for clarifying. Seems my impatience got the better of me, works without a space also!

A couple of tools worth considering (I know the intention is to be conservative):

* Loki (reduce complexity) from Grafana
* Jenkins-x SSO (or similar). Increases complexity but gets around the current requirement of `oauth2_proxy` per namespace.
https://github.com/jenkins-x/sso-operator

**Comment by arapulido** [comment]
> Also just as a btw, kubeprod runtime works very well with jenkins-x. GKE + kubeprod + jenkins-x gets you a mini cloud in around 20 mins.

I would be interested in learning a bit more how you use jenkins-x with BKPR. Could you elaborate a bit more here? Thanks!

**Comment by EamonKeane** [comment]
@arapulido 

Sure, the install I use after the kubeprod quickstart is below. The thing I'd like to fix is extending the oauth-proxy to include e.g. the Jenkins master and the other services like monocular that jx installs.

jx install \
    --provider="gke" \
    --domain="${DOMAIN}" \
    --git-api-token="${GITHUB_TOKEN}" \
    --default-admin-password="${DEFAULT_ADMIN_PASSWORD}" \
    --environment-git-owner="logistio" \
    --skip-ingress=true \
    --username="${GCLOUD_USER}" \
    --urltemplate='"uk-{{.Service}}.{{.Domain}}"' \
    --version="${JX_PLATFORM_CHART_VERSION}" \
    --ingress-deployment="nginx-ingress-controller" \
    --ingress-namespace="kubeprod" \
    --ingress-service="nginx-ingress" \
    --namespace='jx' \
    --git-username="${GIT_USERNAME}" \
    --log-level='debug' \
    --docker-registry="gcr.io/${GCLOUD_PROJECT}" \
    --default-environment-prefix='uk'
