### ISSUE TITLE
Elasticsearch 6.x problems under EKS

### ISSUE THREAD

**Issue by falfaro** [bitnami/kube-prod-runtime#427]
EKS seems to cause problems with Elasticsearch 6.x. I've seen the following warning:

```
ERROR: [1] bootstrap checks failed
[1]: max file descriptors [8192] for elasticsearch process is too low, increase to at least [65536]
```

Reference: pires/kubernetes-elasticsearch-cluster#215

**Comment by arapulido** [comment]
Related issue: https://github.com/awslabs/amazon-eks-ami/issues/193

**Comment by sameersbn** [comment]
Workaround for this issue was added in the docs via #430
