### ISSUE TITLE
kibana: make it easier to install plugins

### ISSUE THREAD

**Issue by anguslees** [bitnami/kube-prod-runtime#453]
There is currently no _easy_ declarative method to install kibana plugins afaics :(

We should add an initContainer that runs `kibana-plugin install ...`, and add a shared plugins volume between that initContainer and the regular kibana container.   See the [helm chart](https://github.com/helm/charts/blob/8ca2d5d8c9cc8a1c828b23b4e57e9d32097635b4/stable/kibana/templates/deployment.yaml#L71) for inspiration.

_Originally posted by @anguslees in https://github.com/bitnami/kube-prod-runtime/issues/386#issuecomment-475081671_

**Comment by sameersbn** [comment]
Implemented in #530
