### ISSUE TITLE
Cleanup option handling

### ISSUE THREAD

**Issue by anguslees** [bitnami/kube-prod-runtime#46]
Currently we pass _some_ options to jsonnet, and some other option to the platform-specific setup code (post-jsonnet), and some options to both.  This is a mess, and doesn't make any of it very transparent to power users.

## Proposal

Replace it all with:
1. pre-jsonnet setup code that does platform-specific setup,
2. write a jsonnet file that has all the generated secrets/option/etc and imports the standard platform,
3. run kubecfg (or embedded library equivalent) on this jsonnet file.

This makes the generated file a good example of how power users can further tweak the setup if they want.  They can also skip the auto-installer entirely if required, etc.

In future we can use sealed-secrets (or similar) to protect the secrets that will be included in this file - for a first version I suggest just writing the naive (plaintext) Secrets.

**Comment by arapulido** [comment]
This was done
