### ISSUE TITLE
GKE 1.12 support

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#465]
Thanks for the update to oauth-proxy!

I've been using `bkpr 1.2` on GKE `1.12` for the past week and it's working fine (I note support is on the next milestone). Is there anything in particular that you think mightn't work or is it just not tested yet?

**Comment by sameersbn** [comment]
It's just that we've not started testing BKPR on K8S 1.12. I just ran the test suite on 1.12 and it passed without any issues. It should be safe to use BKPR 1.2 on k8s 1.12. Do let us know if you bump into any issues :slightly_smiling_face:
