### ISSUE TITLE
`trimUrl` seems to trim the beginning of the URL too?

### ISSUE THREAD

**Issue by hausdorff** [bitnami/kube-prod-runtime#481]
Entirely possible I'm missing something, and I have not tested on real code, but I was perusing the code and [this line](https://github.com/bitnami/kube-prod-runtime/blob/master/manifests/lib/utils.libsonnet#L32) stuck out.

```jsonnet
  trimUrl(str):: (
    if std.endsWith(str, "/") then
      std.substr(str, 1, std.length(str) - 1)
    else
      str
  ),
```

Am I completely misunderstanding, or does that slice the _first_ character off the string, in addition to the last?

**Comment by anguslees** [comment]
Hrm, I think you are quite correct.  I wonder why that never caused an issue before :confused:

In the current manifests, we only use this function [here](https://github.com/bitnami/kube-prod-runtime/blob/c9765605fcea0a82cbcd364ddc951ef2249d0a95/manifests/components/prometheus.jsonnet#L35), in building the configmap-reloader URLs for alertmanager and prometheus sidecars.  So it's possible that the resulting value has been broken before and we just didn't notice in these non-critical sidecars.

Thanks for reporting it!

**Comment by falfaro** [comment]
I will take a look.

**Comment by falfaro** [comment]
https://github.com/bitnami/kube-prod-runtime/pull/487

**Comment by falfaro** [comment]
Fixed.
