### ISSUE TITLE
External-DNS noisy logs in 1.3.1

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#538]
The following appears in the logs of external dns on `1.3.1` every second or two.

```
ERROR: logging before flag.Parse: E0513 11:43:53.421116       1 round_trippers.go:291] CancelRequest not implemented
ERROR: logging before flag.Parse: E0513 11:43:53.421282       1 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
```

A fix for it is on external dns master and will soon be in `0.5.14`. Just mentioning it here in case others see it.
https://github.com/kubernetes-incubator/external-dns/pull/991

**Comment by sameersbn** [comment]
external-dns has been updated to version `0.5.17` and available since versions https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.3.5 and https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.2.7.

Thanks for reporting the issue here
