### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#613]
Congrats on the acquisition by VMWare! 

I know July/August were the summer with people moving and with the acquisition there would likely be a review of the bitnami portfolio and decisions made about which projects to focus on to complement the broader VMWare strategy.

I hope it's ok to ask but I'm just wondering if this project has been selected to maintain? Fingers crossed, I'm a big fan of kube-prod-runtime!

**Comment by sameersbn** [comment]
Hi! We appreciate your interest in the BKPR.

While no new features are currently planned, BKPR is under active maintenance and we plan to continue supporting newer releases of Kubernetes.

We welcome the community to engage and support the development of the project through bug fixes and code contributions.

**Comment by EamonKeane** [comment]
Hi @sameersbn , ah that's great news, thanks! Still don't think there's anything quite like this out there... need to wrangle several operators/helm charts to get this setup.
