### ISSUE TITLE
Tencent Kubernetes Engine (TKE) Support

### ISSUE THREAD

**Issue by skinlayers** [bitnami/kube-prod-runtime#650]
https://intl.cloud.tencent.com/document/product/457

I'm still new to Golang, but I'm happy to help work on this.

**Comment by sameersbn** [comment]
Hi! We appreciate your interest in the BKPR.

While no new features are currently planned, BKPR is under active maintenance and we plan to continue supporting newer releases of Kubernetes.

We welcome the community to engage and support the development of the project through bug fixes, support for new kubernetes service providers and other code contributions.

For adding TKE support, you can start by adding a new platform in `manifests/platforms` and manually testing them using `kubecfg`. Basic jsonnet knowledge is required to understand and extend the manifests.

BKPR requires a OAUTH provider for managing authentication, but you should be able to disable this until you have a working set of manifests.

For DNS configuration, BKPR uses external-dns. Unfortunately external-dns current does not have support for Tencent Cloud DNS (https://github.com/kubernetes-sigs/external-dns#the-latest-release-v05). You can get around this by adding a wildcard domain for all BKPR services.

**Comment by sameersbn** [comment]
@skinlayers Please take a look at #731

**Comment by sameersbn** [comment]
#731 closes this issue
