### ISSUE TITLE
kube-state-metrics pod is not working in recent Kubernetes versions

### ISSUE THREAD

**Issue by irizzant** [bitnami/kube-prod-runtime#655]
Due to the same API deprecations/changes reported [here](https://www.ibm.com/cloud/blog/announcements/kubernetes-version-1-16-removes-deprecated-apis) , the current ClusterRole defined [here](https://github.com/bitnami/kube-prod-runtime/blob/d34d162c9f91f7eb3b5a73f584d226ad28bd438d/manifests/components/prometheus.jsonnet#L442l) doesn't work anymore in recent Kubernetes versions (e.g 1.16) because pod `kube-state-metrics pod` doesn't get the needed authorizations to poll metrics.

**Comment by sameersbn** [comment]
updated in #687
