### ISSUE TITLE
PrincipalNotFound on bootstraping Kubernetes cluster with BKPR

### ISSUE THREAD

**Issue by cpansegrouw** [bitnami/kube-prod-runtime#665]
Im following the quickstart-aks doc. 
At [Step 2 ](https://github.com/bitnami/kube-prod-runtime/blob/master/docs/quickstart-aks.md#step-2-deploy-bkpr) I get the following error : 

```
Installing platform aks
INFO  Created Azure DNS zone "****.*****.com"
INFO  You will need to ensure glue records exist for ****.*****.com pointing to NS [ns1-03.azure-dns.com. ns2-03.azure-dns.net. ns3-03.azure-dns.org. ns4-03.azure-dns.info.]
ERROR Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal ************ does not exist in the directory **********."
```
Im using kubeprod v1.2.7 , azure-cli 2.0.77

Is there anything I can do from my side ?

**Comment by sameersbn** [comment]
I am not sure what the issue is here. Can you try logging in to the azure portal and add the service principal to the active directory?

**Comment by sameersbn** [comment]
@jbianquetti-nami do you have any ideas about the configuration that's required on azure portal for this?

**Comment by jbianquetti-nami** [comment]
Yep, it looks like the user/RBAC account he's using to deploy the product can't be found. 
I would increase the output verbosity and double-check names/users at Azure AD

**Comment by cpansegrouw** [comment]
Yea.
I tried some more stuff. I've been trying to use the `southafricanorth` location to setup my AKS cluster. If I used another location like `europenorth` everything works fine. 
For some reason no service principal is being created via azure-cli if you use the `southafricanorth` location.  
I could manage to get things working by manually creating a service principal and assign it to the aks cluster via the portal. I assume some of the azure rest api's that azure-cli is using is not correctly configured on at this location.

Thanks for pointing me in the correct direction.

**Comment by dayglo** [comment]
I had this exact same issue. Replication of the ```Kubeprod External DNS support for $AZURE_AKS_CLUSTER.bkpr.az.happy-toast.com``` SP in some zones takes a lot longer.

This timeout needs to be longer, maybe a few minutes: https://github.com/dayglo/kube-prod-runtime/blob/ab8a5ebfb3e1e6043f53c6d676436073db538619/kubeprod/pkg/aks/platform.go#L50

I just suspend my terminal for a bit and then unpause it and I don't get the error anymore.

**Comment by raefezzeldin** [comment]
I have tried to increase the number in line 50 but I am still facing the same issue (westeurope)
