### ISSUE TITLE
Cert-manager 0.7 deprecation by lets-encrypt

### ISSUE THREAD

**Issue by EamonKeane** [bitnami/kube-prod-runtime#669]
I'm not sure if this is being enforced right now - but it was announced by Let's Encrypt that they would block cert renewals from cert-manager versions below 0.8 from November 1 due to potential spamming issues during retries. Kubeprod is currently on 0.7.2. I did get a renewal of a cert by kubeprod 0.7.2 in November, so perhaps the version header is different in bitnami's image leading them to still accept them.

In any event - perhaps a short term bump of cert-manager to a supported version would be a good idea (I know the most recent version 0.12.0 probably is more involved due to the introduction of CRDs).

https://community.letsencrypt.org/t/blocking-old-cert-manager-versions/98753

**Comment by sameersbn** [comment]
@EamonKeane thanks for letting us know. We will work on updating the version and resolve the issue

**Comment by sameersbn** [comment]
@EamonKeane I've just tagged BKPR [1.3.6](https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.3.6) with cert-manager 0.12.0. The release should be up in a while. Please refer to the migration guide for pre-upgrade instructions.

**Comment by EamonKeane** [comment]
great, thanks @sameersbn !

**Comment by jjo** [comment]
> @EamonKeane I've just tagged BKPR [1.3.6](https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.3.6) with cert-manager 0.12.0. The release should be up in a while. Please refer to the migration guide for pre-upgrade instructions.

@sameersbn 
Be careful that cert-manager 0.10+ comes with a slew of changes: https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/, modifying both their own manifests (CRDs, deployments, etc) _and_ ingress annotations.

If it was for LE compatibility, latest 0.10 would be a much safer choice.
