### ISSUE TITLE
[ACTION REQUIRED] k8s.gcr.io moving from gcr.io/google-containers to gcr.io/k8s-artifacts-prod in early April

### ISSUE THREAD

**Issue by jbianquetti-nami** [bitnami/kube-prod-runtime#740]
from https://groups.google.com/forum/m/#!topic/kubernetes-dev/MkXnkTSJ_vs: 

On April 1, 2020* the k8s.gcr.io vanity domain will flip to gcr.io/k8s-artifacts-prod, which is community owned. Just before the flip, gcr.io/google-containers will enter a read-only freeze.

For BKPR: https://github.com/bitnami/kube-prod-runtime/search?q="k8s.gcr.io"&unscoped_q="k8s.gcr.io"

**Comment by sameersbn** [comment]
@jbianquetti-nami doesn't this mean the images can still be downloaded from the same registry url? As I understand it only the backing store will flip to `gcr.io/k8s-artifacts-prod` requiring image maintainer to push new images to this location. 

Is there anything I am missing here?

**Comment by jbianquetti-nami** [comment]
You're right: `k8s.gcr.io` will continue serving the assets,  so no action needed. Sorry for the noise. Closing this.
