### ISSUE TITLE
plans/timeline to support k8s 1.16

### ISSUE THREAD

**Issue by bradleyhd** [bitnami/kube-prod-runtime#752]
Hi!

GCP is starting to send out emails for GKE saying that 1.16 is going to be made available in the regular release channel, with automatic upgrades (if enabled) starting 2020-04-09.

1.16 appears to deprecate several APIs used for BKPR including `apps/v1beta1`, so... is work to support 1.16 underway? is there a timeline? is there something a k8s n00b like me can do to help?

Thanks.

**Comment by beltran-rubo** [comment]
Hi @bradleyhd 

We plan to work on this in the next 2-3 weeks. We will keep you in the loop when we release a new version.
