### ISSUE TITLE
Is it possible to configure BKPR to use an external Elastic stack?

### ISSUE THREAD

**Issue by cccs-eric** [bitnami/kube-prod-runtime#761]
Hi,

  We have multiple AKS clusters where some are using BKPR, others are not.  But they all use Elasticsearch to store applications logging.  We would like to consolidate all our application logs into a centralized Elastic stack.  Is it possible to configure BKPR to redirect fluentd to send the logs to an external Elasticsearch?  Or would you recommend another approach?

Thank you

**Comment by javsalgar** [comment]
Hi,

kubeprod will generate jsonnet files with all the components. What you could do is to edit these files so it does not deploy the EFK resources and instead uses the ones you already have in place. This way, you can only deploy components like Prometheus, external-dns and others.

**Comment by jjo** [comment]
Please follow https://github.com/bitnami/kube-prod-runtime/blob/master/docs/overrides.md, the specific override for your case, assuming GKE would be something like:

```
// Cluster-specific configuration
(import "manifests/platforms/gke.jsonnet") {
        config:: import "kubeprod-autogen.json",
        // Place your overrides here
  // Using `::` to remove elasticsearch stanza, then overloading
  // svc.host field to let fluentd_es and kibana point to it instead
  elasticsearch:: {
    svc:: {
      host: "elasticsearch.example.com:9200",
    },
  },
}
```
obviously replacing `host` value by your elasticsearch endpoint.
