### ISSUE TITLE
AKS install error

### ISSUE THREAD

**Issue by dayglo** [bitnami/kube-prod-runtime#777]
I'm struggling to get installed on AKS. 

The installer gets to ```Updating statefulset kubeprod.alertmanager``` but then says 

```ERROR Error: unable to fetch resource description for apps/v1beta2: the server could not find the requested resource```

I can't figure out from the code why this isnt working. Pls can you help?

```
...
....
INFO  Updating services kubeprod.alertmanager
DEBUG Using resource 'services' for /v1, Kind=Service
DEBUG Fetching client for &APIResource{Name:services,Namespaced:true,Kind:Service,Verbs:[create delete get list patch update watch],ShortNames:[svc],SingularName:,Categories:[all],Group:,Version:,} namespace=kubeprod
DEBUG Patch(alertmanager) returned (&{map[apiVersion:v1 kind:Service metadata:map[annotations:map[kubecfg.ksonnet.io/garbage-collect-tag:kube_prod_runtime] creationTimestamp:2020-04-22T01:40:59Z labels:map[kubecfg.ksonnet.io/garbage-collect-tag:kube_prod_runtime name:alertmanager] name:alertmanager namespace:kubeprod resourceVersion:1980 selfLink:/api/v1/namespaces/kubeprod/services/alertmanager uid:c58c1746-d2c5-474f-bf7d-998d0ed23bcf] spec:map[clusterIP:10.0.94.81 ports:[map[name:alertmanager port:9093 protocol:TCP targetPort:9093]] selector:map[name:alertmanager] sessionAffinity:None type:ClusterIP] status:map[loadBalancer:map[]]]}, <nil>)
DEBUG Updated object: {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kubecfg.ksonnet.io/garbage-collect-tag":"kube_prod_runtime"},"

A: labels":{"kubecfg.ksonnet.io/garbage-collect-tag":"kube_prod_runtime","name":"alertmanager"},"name":"alertmanager","namespace":"kubeprod"},"spec":{"ports":[{"name":"alertmanager","port":9093,"targetPort":9093}],"selector":{"name":"alertmanager"},"type":"ClusterIP"}}

B: creationTimestamp":"2020-04-22T01:40:59Z","labels":{"kubecfg.ksonnet.io/garbage-collect-tag":"kube_prod_runtime","name":"alertmanager"},"name":"alertmanager","namespace":"kubeprod","resourceVersion":"1980","selfLink":"/api/v1/namespaces/kubeprod/services/alertmanager","uid":"c58c1746-d2c5-474f-bf7d-998d0ed23bcf"},"spec":{"clusterIP":"10.0.94.81","ports":[{"name":"alertmanager","port":9093,"protocol":"TCP","targetPort":9093}],"selector":{"name":"alertmanager"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
DEBUG Discovery failed for apps/v1beta2, Kind=StatefulSet: the server could not find the requested resource, falling back to kind
INFO  Updating statefulset kubeprod.alertmanager
ERROR Error: unable to fetch resource description for apps/v1beta2: the server could not find the requested resource
```

**Comment by dayglo** [comment]
im on k8s 1.16.7 btw

**Comment by javsalgar** [comment]
Hi,

This is very strange, it seems to me that the kube.libsonnet library that is using is old, because it is using a deprecated API group for the Statefulset. Could you confirm that you are using the latest BKPR version?

**Comment by jjo** [comment]
> Hi,
> 
> This is very strange, it seems to me that the kube.libsonnet library that is using is old, because it is using a deprecated API group for the Statefulset. Could you confirm that you are using the latest BKPR version?

@javsalgar Master already have the fixes from #770, but we didn't yet created v1.6.0 branch + release for it, let's work on that :)

**Comment by dayglo** [comment]
Here's the output from kubeprod version 

```
Installer version: v1.5.0
Server manifests version: not installed```

Maybe that second bit is my problem. Ill have a dig and try figure out what that means.

**Comment by dayglo** [comment]
I think I figured out where I went wrong. I rolled back my deploy script and ended up with k8s 1.17.3. Ill redeploy and try again. Really sorry if i wasted anyones time.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. Please let us know if the installation this time went well.

**Comment by dayglo** [comment]
I just tried it again with k8s 1.16.7 and I get the same error message. I downgraded kubectl just in case but that didn't help either... 

How would i check where I'm loading the kube.libsonnet library from? 

(sorry i dont know golang yet)

**Comment by jjo** [comment]
We're working on 1.6.0-rc release that should fix this (it's there already in release-1.6, need to tag + release) /cc @javsalgar

**Comment by jjo** [comment]
> We're working on 1.6.0-rc release that should fix this (it's there already in release-1.6, need to tag + release) /cc @javsalgar

@dayglo : Could you please try 1.6.0 as released at https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.6.0-rc1, and let us know how it goes ?
Thanks! --jjo

**Comment by dayglo** [comment]
Hi @jjo. That release candidate executed cleanly.

Thanks for your help! Ill go and kick the tyres. This seems like a great project, I can't wait to ditch all the terraform I've been using for this stuff 🖖

**Comment by jjo** [comment]
> Hi @jjo. That release candidate executed cleanly.
> 
> Thanks for your help! Ill go and kick the tyres. This seems like a great project, I can't wait to ditch all the terraform I've been using for this stuff

w00T, that's great news! , thanks for confirming, so-much appreciated :)

**Comment by javsalgar** [comment]
Awesome! Do not hesitate to open a new ticket if you find more issues :)

**Comment by jjo** [comment]
Fixed as per above, we'll be releasing a new `v1.6.0-rc` cut soon with some small (not related) fixes.
