### ISSUE TITLE
v1.6.0-rc1: All ingresses fail in Safari

### ISSUE THREAD

**Issue by SailingYYC** [bitnami/kube-prod-runtime#815]
Standard install of BKPR v1.6.0-rc1 on AKS (k8s v1.16.7)

When attempting to go to any ingress in Safari on Catalina:
`Safari Can’t Open the Page: Safari can’t open the page. The error is: “The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 303.)” (kCFErrorDomainCFNetwork:303)`. However, the same ingresses load in Chrome and with `curl`/`curl --http2`.

After researching and testing, https://stackoverflow.com/questions/49927327/website-ok-on-firefox-but-not-on-safari-kcferrordomaincfnetwork-error-303-neit#answer-50442837 resolved the issue, by adding the following to the `nginx-ingress` configMap:

```
http2-max-field-size: 16k
http2-max-header-size: 128k
```

I don't know if this resolves the underlying problem, or is masking it.

**Comment by javsalgar** [comment]
Hi,

Could you confirm that this issue does not occur with browsers like Chrome or Firefox?

**Comment by SailingYYC** [comment]
Hi @javsalgar,

I can confirm that, prior to changing the configuration, the following did work:
- Google Chrome 81.0.4044.138 using HTTP2
- Firefox 76.0.1 using HTTP2
- Insomnia 7.1.1 using HTTP2
- `curl --http2`
- `curl`

**Comment by javsalgar** [comment]
Hi,

Thank you very much for your feedback, we could consider adding this feature to BKPR by default so it also works in Safari.

**Comment by jjo** [comment]
Also found at https://github.com/kubernetes/ingress-nginx/issues/3499 (which looks related to the auth ingress setup), there also found the fix to be:
```
http2-max-field-size: "16k"
http2-max-header-size: "64k"
```
