### ISSUE TITLE
 v1.6.0-rc2 RUNTIME ERROR: Couldn't open import "../lib/kube.libsonnet"

### ISSUE THREAD

**Issue by DavidSchargel** [bitnami/kube-prod-runtime#837]
A brand new AWS account and following EKS Getting Started docs. Using downloaded bkpr-v1.6.0-rc2-linux-amd64.tar.gz

Everything was going great until I got to kubeprod step. It _appears_ that multiple files are missing from /manifests folder when untaring, but I could be wrong.

`
> kubeprod install eks \
>   --email ${AWS_EKS_USER} \
>   --dns-zone "${BKPR_DNS_ZONE}" \
>   --user-pool-id "${AWS_COGNITO_USER_POOL_ID}"
`

```
INFO  Installing platform eks
INFO  Setting up configuration for External DNS
INFO  Created AKS user: bkpr-XXXXXXXXXXXX.com
WARNING Re-using exting Route 53 hostedzone/XXXXXXXXXXXX for External DNS integration: XXXXXXXXXXXX.com.
INFO  Created IAM policy for External DNS integration: arn:aws:iam::XXXXXXXXXXXX:policy/bkpr-XXXXXXXXXXXX.com
INFO  Attached IAM policy for External DNS integration
INFO  Setting up configuration for OAuth2 Proxy
INFO  Created new client in user pool 'us-west-2_XXXXXXXXXXXX' for OAuth2 proxy integration: XXXXXXXXXXXX
INFO  Writing cluster settings to "/home/david/kubeprod-autogen.json"
INFO  Using manifests from https://releases.kubeprod.io/files/v1.6.0-rc2/manifests/platforms/eks.jsonnet
INFO  Deploying Bitnami Kubernetes Production Runtime for platform eks
INFO  Updating platform eks
ERROR Error: RUNTIME ERROR: Couldn't open import "../lib/kube.libsonnet", no match locally or in library search paths. Tried: https://releases.kubeprod.io/files/v1.6.0-rc2/manifests/lib/kube.libsonnet;internal:///lib/kube.libsonnet
        https://releases.kubeprod.io/files/v1.6.0-rc2/manifests/components/cert-manager.jsonnet:20:14-44        thunk <kube> from <$>
        https://releases.kubeprod.io/files/v1.6.0-rc2/manifests/components/cert-manager.jsonnet:52:28-32
        During manifestation
```

**Comment by DavidSchargel** [comment]
I should have also mentioned that I got the same error when cloning the repository. The lib symbolic link was there and resolved correctly to vendor, but still the same error.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for using BKPR. I was able to reproduce the issue. Indeed, the files are missin. @jjo could it be an issue with the release bucket where we store the manifests?

**Comment by jjo** [comment]
> Hi,
> 
> Thank you very much for using BKPR. I was able to reproduce the issue. Indeed, the files are missin. @jjo could it be an issue with the release bucket where we store the manifests?

Thanks much indeed for the report, and yup we've scheduled tackling this during this iteration -- it's related to the vendor/ing I did to include kube-libsonnet (vs embedded in as it was before)

**Comment by jjo** [comment]
FYI @DavidSchargel we've just merged the fixes, will cut a new `-rc` soon

**Comment by jjo** [comment]
FYI https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.6.0-rc3 has been released.
