### ISSUE TITLE
Support for EKS 1.15 in BKPR 1.5.Y

### ISSUE THREAD

**Issue by vejmelkam** [bitnami/kube-prod-runtime#838]
Hi, while reviewing the support matrix I noticed that only k8s 1.14 is supported on EKS while 1.14 AND 1.15 on both AKS and GKE. Is there a reason for this (known problems) or is this due to testing only using those version combinations? I ask since there doesn't seem to be an upgrade path to BKPR 1.6 (since that doesn't support 1.14). An upgrade path exists for other cloud providers (BKPR 1.5.X -> k8s 1.15 -> BKPR 1.6.0 -> k8s 1.16). Can you shed some light on this please?

**Comment by javsalgar** [comment]
Hi,

Sorry for the delay. We would need to confirm it but it is highly likely that it's due to the fact that 1.15 support in EKS is quite recent (10 Mar 2020): https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-eks-now-supports-kubernetes-version-1-15/

@jjo do you recall any reason for not being compatible with k8s 1.15?

**Comment by javsalgar** [comment]
Hi,

Checking the kubeprod code, I would like to know the kind of tokens you get in this case and how the kubeprod installer recognizes them. Could you try again with a higher log level so the installer shows more verbosity? 

More context here: https://github.com/bitnami/kube-prod-runtime/blob/1782882ecefb4cb3d2a469fb075f7a2bf2b65222/kubeprod/vendor/github.com/Azure/go-autorest/autorest/azure/cli/token.go#L73

**Comment by vejmelkam** [comment]
Hi @javsalgar thanks for your response - and thanks to all BKPR authors for this fantastic tech stack! So far it has been working great.

Maybe this will be helpful: we have internally reviewed for potential blockers (with @alenkacz), haven't found any, and decided to try the upgrade on our staging cluster. That cluster has been running problem free for 1-2 weeks now and our application is running fine. I am holding off upgrading the prod cluster UNTIL I verify that the upgrade 1.5.0 to 1.6.0 (when it comes out) will also work on staging. Once that path succeeds, we plan to do exactly that sequence for prod (1.5.0 BKPR & 1.14 EKS -> 1.5.0 BKPR & 1.15 EKS -> 1.6.0 BKPR & 1.15 EKS) and then move to 1.16 EKS.

Let me know if we can supply some relevant testing info.

**Comment by jjo** [comment]
Thanks @vejmelkam for bringing this up

> Hi,
> 
> Sorry for the delay. We would need to confirm it but it is highly likely that it's due to the fact that 1.15 support in EKS is quite recent (10 Mar 2020): https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-eks-now-supports-kubernetes-version-1-15/
> 
> @jjo do you recall any reason for not being compatible with k8s 1.15?

Surely that's the reason, I'm currently working on bringing `release-1.5` build and testing pipeline closer to master (and `release-1.6`).
Once I have that in place it should be pretty easy to add `1.15` to to `release-1.5`, and likely succeed doing so, as the _big_ `apiVersion` deprecation happened on 1.16, I'll work on it.

**Comment by jjo** [comment]
@vejmelkam  #854 has been merged, successfully adding EKS 1.15 to our e2e testing pipeline -- there have been no code changes per-se (`Jenkinsfile` and small docu adjusts), so you'd just need to use our latest v1.5.x release.
