### ISSUE TITLE
addon-resizer eats Deployment affinity/tolerations (needs newer version)

### ISSUE THREAD

**Issue by anguslees** [bitnami/kube-prod-runtime#85]
An external `kubecfg` user encountered this (and initially thought it was a `kubecfg` bug).  We will encounter the same issue with addon-resizer too.  Apparently the fix is to upgrade to (at least) `k8s.gcr.io/addon-resizer:1.8.3`

See also: https://github.com/kubernetes/autoscaler/issues/188

**Comment by arapulido** [comment]
@anguslees is this still relevant?

**Comment by anguslees** [comment]
Yes, we're still using `gcr.io/google_containers/addon-resizer:1.0` in the prometheus manifests.
