### ISSUE TITLE
v1.6.0: Missing symlinks from bkpr-v1.6.0-linux-amd64.tar.gz

### ISSUE THREAD

**Issue by andrew-zimmerman-rseg** [bitnami/kube-prod-runtime#886]
Deploying kubeprod on a brand new AKS I ran into the following error on bkpr v1.6.0:

`ERROR Error: RUNTIME ERROR: Couldn't open import "grafana-dashboards/handcrafted/kubernetes/k8s_cluster_capacity.json", no match locally or in library search paths. Tried: file:///usr/lib/bkpr/manifests/components/grafana-dashboards/handcrafted/kubernetes/k8s_cluster_capacity.json;internal:///grafana-dashboards/handcrafted/kubernetes/k8s_cluster_capacity.json
	file:///usr/lib/bkpr/manifests/components/grafana.jsonnet:126:36-115	object <anonymous>
	file:///usr/lib/bkpr/manifests/vendor/github.com/bitnami-labs/kube-libsonnet/kube.libsonnet:343:19-31	thunk from <object <anonymous>>
	file:///usr/lib/bkpr/manifests/vendor/github.com/bitnami-labs/kube-libsonnet/kube.libsonnet:343:10-32	object <anonymous>
		builtin function <flatMap>
	file:///usr/lib/bkpr/manifests/vendor/github.com/bitnami-labs/kube-libsonnet/kube.libsonnet:345:23-33	thunk from <object <anonymous>>
	file:///usr/lib/bkpr/manifests/vendor/github.com/bitnami-labs/kube-libsonnet/kube.libsonnet:345:12-34	object <anonymous>
	file:///usr/lib/bkpr/manifests/vendor/github.com/bitnami-labs/kube-libsonnet/kube.libsonnet:332:24-42
	During manifestation`

Unzipping the tar file (even with the -h option) it seems that the symlinks [here](https://github.com/bitnami/kube-prod-runtime/blob/master/manifests/vendor/kubernetes-grafana-dashboards) and [here](https://github.com/bitnami/kube-prod-runtime/blob/master/manifests/vendor/kube-libsonnet) are not shipped as part of the package and causing these failures.

**Comment by javsalgar** [comment]
@jjo could this be an issue in the latest CI/CD changes?

**Comment by jjo** [comment]
> @jjo could this be an issue in the latest CI/CD changes?

This was fixed by #884 (using full-path for vendor-ed imports instead of symlinks), will cut v1.6.1 for it.

**Comment by jjo** [comment]
@andrew-zimmerman-rseg : https://github.com/bitnami/kube-prod-runtime/releases/tag/v1.6.1 is now released, appreciate if you can test it and feedback, thanks!

**Comment by andrew-zimmerman-rseg** [comment]
Tested this out today and things look good on v1.6.1. Was able to get a successful deploy. Thanks for the quick turnaround!

**Comment by jjo** [comment]
Awesome, thanks Andrew for feeding back!
